version: '3'
services:
  order-service:
    image: order-service:latest
    build: ./order-service
    ports:
      - "8081:8080"
    depends_on:
      - postgres
      - rabbitmq

  inventory-service:
    image: inventory-service:latest
    build: ./inventory-service
    ports:
      - "8082:8080"
    depends_on:
      - postgres
      - rabbitmq

  payment-service:
    image: payment-service:latest
    build: ./payment-service
    ports:
      - "8083:8080"
    depends_on:
      - postgres
      - rabbitmq

  shipping-service:
    image: shipping-service:latest
    build: ./shipping-service
    ports:
      - "8084:8080"
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orderdb
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
